spring:
 application:
   name: USER-SERVICE

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Hotel_Management_System
    username: root
    password: root@123

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

server:
  port: 8082

logging:
  level:
    org.springframework: INFO

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
